create table articles (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar
(255) NOT NULL);

CREATE table comments(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    commentBody varchar
(255) NOT NULL,
    userId varchar
(255) NOT NULL
);  